const FLOW_META = {
  associate: {
    id: 'associate',
    label: 'Associate Tour',
    shortLabel: 'Associate',
    audience: 'External Associate',
  },
  admin: {
    id: 'admin',
    label: 'Admin / Ops Tour',
    shortLabel: 'Admin',
    audience: 'Admin and Ops',
  },
  field: {
    id: 'field',
    label: 'Field / Employee Tour',
    shortLabel: 'Field',
    audience: 'Field and employee users',
  },
}

const MOBILE_FLOW_VARIANTS = {
  associate: {
    duration: '5 minutes',
    summary: 'Learn the structured associate loop: intake, evidence, and status tracking.',
    steps: [
      {
        id: 'associate-home',
        route: '/m/home',
        routePattern: '^/m/home$',
        target: '[data-tour-id="demo-mission-panel"]',
        title: 'Welcome To Mobile Home',
        explanation: 'This is your control surface for requests, uploads, and status movement.',
        whyItMatters: 'Associates should not guess where work is stuck. The mobile home condenses the current workload into a single view.',
        actionText: 'Review the mission panel, then use it to move into the first intake step.',
        expectedResult: 'You know where to restart the tutorial and where to monitor draft or missing-file pressure.',
      },
      {
        id: 'associate-request-form',
        route: '/m/request/new',
        routePattern: '^/m/request/new(?:\\?.*)?$',
        target: '[data-tour-id="mobile-associate-request-form"]',
        title: 'Open The Associate Request Composer',
        explanation: 'This form captures a structured intake instead of relying on chat or ad-hoc calls.',
        whyItMatters: 'A clean intake gives operations the minimum context needed to start the case without corrupting permanent records.',
        actionText: 'Fill the essential service-line, borrower, branch, and property details.',
        expectedResult: 'The request has enough context to be saved as a controlled draft or submitted for review.',
      },
      {
        id: 'associate-request-submit',
        route: '/m/request/new',
        routePattern: '^/m/request/new(?:\\?.*)?$',
        target: '[data-tour-id="mobile-associate-request-submit"]',
        title: 'Save Or Submit With Intent',
        explanation: 'Maulya lets you preserve work-in-progress safely before operations reviews it.',
        whyItMatters: 'This keeps intake disciplined. Missing details are visible early, not discovered during release or payment follow-up.',
        actionText: 'Use Save Draft when gathering more data, or Submit Request when the intake is clean enough to review.',
        expectedResult: 'The request transitions into a visible tracked state instead of disappearing into informal communication.',
      },
      {
        id: 'associate-assignments-list',
        route: '/m/assignments',
        routePattern: '^/m/assignments(?:\\?.*)?$',
        autoAdvanceOnRoute: true,
        target: '[data-tour-id="mobile-assignments-list"]',
        title: 'Track Active Requests',
        explanation: 'The assignments list shows the visible request queue and the latest movement on each item.',
        whyItMatters: 'Associates need a single place to confirm whether a request is still draft, in review, or waiting on evidence.',
        actionText: 'Open the most relevant request from the list to inspect details and next actions.',
        expectedResult: 'You move from the queue into a single request detail page with clear operational context.',
      },
      {
        id: 'associate-assignment-detail',
        route: '/m/assignments/:id',
        routePattern: '^/m/assignments/[^/]+$',
        autoAdvanceOnRoute: true,
        routeSourceTarget: '[data-tour-id="mobile-assignments-list"] [data-tour-route]',
        target: '[data-tour-id="mobile-assignment-summary"]',
        title: 'Read The Request Status In Context',
        explanation: 'The request detail screen summarizes code, status, customer context, and what needs to happen next.',
        whyItMatters: 'This is where status becomes operationally meaningful instead of just cosmetic. It tells you whether the case is moving or blocked.',
        actionText: 'Review the summary and note the next-action guidance before moving to evidence handling.',
        expectedResult: 'You understand the request state and know whether the next move is upload, clarification, or waiting for review.',
      },
      {
        id: 'associate-uploads',
        route: '/m/assignments/:id/uploads',
        routePattern: '^/m/assignments/[^/]+/uploads$',
        autoAdvanceOnRoute: true,
        target: '[data-tour-id="mobile-uploads-progress"]',
        title: 'Complete Evidence And Checklist Work',
        explanation: 'Uploads and checklist progress live here so required evidence is visible before downstream teams touch the file.',
        whyItMatters: 'Evidence discipline reduces approval churn and prevents avoidable report or payment delays.',
        actionText: 'Review missing items, then upload one supporting document or image into the request.',
        expectedResult: 'Checklist progress improves and the request becomes easier for operations to review without follow-up noise.',
      },
      {
        id: 'associate-status-close',
        route: '/m/assignments/:id',
        routePattern: '^/m/assignments/[^/]+$',
        autoAdvanceOnRoute: true,
        target: '[data-tour-id="mobile-assignment-status"]',
        title: 'Finish The Associate Loop',
        explanation: 'After intake and evidence, Maulya keeps the request visible through approval and follow-up status.',
        whyItMatters: 'The product value is not just form capture. It is controlled movement from request to review without losing accountability.',
        actionText: 'Return to the request detail and confirm where status and next action are shown.',
        expectedResult: 'You can now intake, upload, and track a request through the live associate workflow.',
      },
    ],
  },
  admin: {
    duration: '6 minutes',
    summary: 'Follow approvals, evidence review, and payment control from the mobile workspace.',
    steps: [
      {
        id: 'admin-home',
        route: '/m/home',
        routePattern: '^/m/home$',
        target: '[data-tour-id="demo-mission-panel"]',
        title: 'Start From The Mobile Control Surface',
        explanation: 'The home screen summarizes what needs action now: approvals, uploads, and invoice pressure.',
        whyItMatters: 'Admin work should start from exceptions and queues, not manual chasing.',
        actionText: 'Use the mission panel to move into the approvals inbox.',
        expectedResult: 'You know where the demo control loop begins.',
      },
      {
        id: 'admin-approvals',
        route: '/m/approvals',
        routePattern: '^/m/approvals(?:\\?.*)?$',
        autoAdvanceOnRoute: true,
        target: '[data-tour-id="mobile-approvals-list"]',
        title: 'Review Approval Pressure',
        explanation: 'The approvals inbox centralizes draft, final-document, and payment decisions.',
        whyItMatters: 'Auditability depends on explicit approve or reject actions with visible reasons.',
        actionText: 'Open a pending approval and inspect the operational context before deciding.',
        expectedResult: 'You understand how decisions stay governed inside the app instead of chat.',
      },
      {
        id: 'admin-invoices',
        route: '/m/invoices',
        routePattern: '^/m/invoices(?:\\?.*)?$',
        autoAdvanceOnRoute: true,
        target: '[data-tour-id="mobile-invoices-list"]',
        title: 'Track Payment Confirmation',
        explanation: 'Invoices show balance pressure and where recorded payments still need confirmation.',
        whyItMatters: 'Cashflow reporting is only trustworthy when payment entries move through approval discipline.',
        actionText: 'Open the invoice list and inspect the add-payment approval flow.',
        expectedResult: 'You understand that paid totals only count after the payment is confirmed.',
      },
    ],
  },
  field: {
    duration: '5 minutes',
    summary: 'Learn how to move from queue to evidence to controlled draft creation on mobile.',
    steps: [
      {
        id: 'field-home',
        route: '/m/home',
        routePattern: '^/m/home$',
        target: '[data-tour-id="demo-mission-panel"]',
        title: 'Use My Day As Your Starting Point',
        explanation: 'The home screen surfaces the queue and the work most likely to stall today.',
        whyItMatters: 'Field work should start from priority, not memory.',
        actionText: 'Review the mission panel and then move into search or queue.',
        expectedResult: 'You know where to begin the day on mobile.',
      },
      {
        id: 'field-search',
        route: '/m/search',
        routePattern: '^/m/search(?:\\?.*)?$',
        autoAdvanceOnRoute: true,
        target: '[data-tour-id="mobile-search-screen"]',
        title: 'Find Work Fast',
        explanation: 'Search is the quickest way to locate a case without digging through long queues.',
        whyItMatters: 'Fast retrieval is essential when field users are switching between calls, visits, and uploads.',
        actionText: 'Search for a live assignment and open it.',
        expectedResult: 'You reach the assignment context you need without browsing manually.',
      },
      {
        id: 'field-create',
        route: '/m/create',
        routePattern: '^/m/create(?:\\?.*)?$',
        autoAdvanceOnRoute: true,
        target: '[data-tour-id="mobile-create-stepper"]',
        title: 'Open The Draft Wizard',
        explanation: 'The mobile draft wizard is the structured path for opening work cleanly from the field.',
        whyItMatters: 'Draft-first intake protects downstream ops from incomplete or malformed assignment creation.',
        actionText: 'Review the three-step wizard and note how it enforces operational basics.',
        expectedResult: 'You understand where controlled draft creation happens on mobile.',
      },
    ],
  },
}

const DESKTOP_FLOW_VARIANTS = {
  associate: {
    duration: '4 minutes',
    summary: 'Learn the structured associate request loop from the desktop workspace.',
    steps: [
      {
        id: 'associate-desktop-home',
        route: '/partner',
        routePattern: '^/partner$',
        target: '[data-tour-id="demo-mission-panel"]',
        title: 'Start From The Associate Dashboard',
        explanation: 'The associate dashboard shows live requests, payment prompts, and the next follow-up at a glance.',
        whyItMatters: 'Associates need one place to monitor intake status without calling operations for routine updates.',
        actionText: 'Review the mission panel, then move into the request workspace.',
        expectedResult: 'You understand where to restart the walkthrough and how the associate dashboard summarizes active work.',
      },
      {
        id: 'associate-desktop-request-form',
        route: '/partner/requests/new',
        routePattern: '^/partner/requests/new(?:\\?.*)?$',
        target: '[data-tour-id="partner-request-form"]',
        title: 'Open The Associate Request Form',
        explanation: 'This desktop form captures a structured request with the minimum customer and property context operations needs.',
        whyItMatters: 'Structured intake reduces ambiguity and keeps review, payment, and delivery steps traceable.',
        actionText: 'Review the request form sections and note how they focus only on associate-supplied data.',
        expectedResult: 'You know where to create a new request without entering internal-only operations data.',
      },
      {
        id: 'associate-desktop-requests-list',
        route: '/partner/requests',
        routePattern: '^/partner/requests(?:\\?.*)?$',
        target: '[data-tour-id="partner-requests-table"]',
        title: 'Track Submitted Requests',
        explanation: 'The request list shows what has been submitted, what needs clarification, and what is ready to move forward.',
        whyItMatters: 'The product value is not just intake. It is ongoing status visibility with less back-and-forth.',
        actionText: 'Open the requests list and confirm where status, payment, and edit actions appear.',
        expectedResult: 'You can track request progress and know where to respond if more information is needed.',
      },
    ],
  },
  admin: {
    duration: '4 minutes',
    summary: 'Review the control loop from the desktop cockpit: dashboard, approvals, and invoice discipline.',
    steps: [
      {
        id: 'admin-desktop-home',
        route: '/admin/dashboard',
        routePattern: '^/admin/dashboard$',
        target: '[data-tour-id="demo-mission-panel"]',
        title: 'Start From Control Tower',
        explanation: 'The desktop dashboard summarizes operational pressure: workload, approvals, overdue cases, and payment exposure.',
        whyItMatters: 'Admin work should begin from exceptions and queue pressure, not manual follow-up or chat.',
        actionText: 'Review the mission panel, then move into the approvals inbox.',
        expectedResult: 'You understand where the demo control loop begins on desktop.',
      },
      {
        id: 'admin-desktop-approvals',
        route: '/admin/approvals',
        routePattern: '^/admin/approvals(?:\\?.*)?$',
        target: '[data-tour-id="admin-approvals-list"]',
        title: 'Review Governed Decisions',
        explanation: 'The approvals inbox keeps draft, final-document, and payment decisions explicit and auditable.',
        whyItMatters: 'Requests should not be approved in side channels. Centralized decisions protect auditability and release discipline.',
        actionText: 'Open the approvals inbox and inspect how status, type, and decision actions are organized.',
        expectedResult: 'You can identify where approval work lives and how the app keeps those decisions visible.',
      },
      {
        id: 'admin-desktop-invoices',
        route: '/invoices',
        routePattern: '^/invoices(?:\\?.*)?$',
        target: '[data-tour-id="desktop-invoices-list"]',
        title: 'Inspect Invoice And Payment Pressure',
        explanation: 'The invoice ledger shows unpaid exposure, aging, and the payment actions that affect reported cashflow.',
        whyItMatters: 'Revenue visibility is only trustworthy when invoice updates and payment confirmations stay governed.',
        actionText: 'Open the ledger and note where filters, aging buckets, and payment controls are surfaced.',
        expectedResult: 'You know where to review invoice status and why payment confirmation is a controlled workflow.',
      },
    ],
  },
  field: {
    duration: '4 minutes',
    summary: 'Learn the desktop staff path from My Day to assignments and governed requests.',
    steps: [
      {
        id: 'field-desktop-home',
        route: '/account',
        routePattern: '^/account(?:\\?.*)?$',
        target: '[data-tour-id="demo-mission-panel"]',
        title: 'Start From My Day',
        explanation: 'My Day prioritizes overdue work, due-soon assignments, and operational signals for the logged-in staff user.',
        whyItMatters: 'Staff should start from the most urgent queue items instead of browsing every assignment manually.',
        actionText: 'Review the mission panel, then move into the assignments queue.',
        expectedResult: 'You know where to begin the day and where to return if priorities change.',
      },
      {
        id: 'field-desktop-assignments',
        route: '/assignments',
        routePattern: '^/assignments(?:\\?.*)?$',
        target: '[data-tour-id="desktop-assignments-table"]',
        title: 'Work The Assignment Queue',
        explanation: 'The assignment queue centralizes filters, saved views, and due-state triage for operational work.',
        whyItMatters: 'Queue discipline is what keeps field and staff work moving without missed deadlines.',
        actionText: 'Open the assignments queue and inspect the worklist, filters, and status columns.',
        expectedResult: 'You understand where to triage work and how to narrow the queue quickly.',
      },
      {
        id: 'field-desktop-requests',
        route: '/requests',
        routePattern: '^/requests(?:\\?.*)?$',
        target: '[data-tour-id="desktop-requests-form"]',
        title: 'Use Governed Request Paths',
        explanation: 'Sensitive leave or approval requests should be raised inside the product, not by informal messages.',
        whyItMatters: 'Governed requests protect auditability and reduce confusion about who approved what.',
        actionText: 'Open the request page and review where approval requests are submitted and tracked.',
        expectedResult: 'You know where to request sensitive actions without leaving the workspace.',
      },
    ],
  },
}

export const DEMO_TUTORIAL_FLOW_ORDER = ['associate', 'admin', 'field']

export function isDemoTutorialFlowId(flowId) {
  return Boolean(FLOW_META[flowId])
}

export function getDemoTutorialFlow(flowId, { surface = 'mobile' } = {}) {
  const meta = FLOW_META[flowId]
  const variants = surface === 'desktop' ? DESKTOP_FLOW_VARIANTS : MOBILE_FLOW_VARIANTS
  const variant = variants[flowId]
  if (!meta || !variant) return null
  return {
    ...meta,
    ...variant,
  }
}

export function getDemoTutorialFlowSummaries({ surface = 'mobile' } = {}) {
  return DEMO_TUTORIAL_FLOW_ORDER
    .map((flowId) => getDemoTutorialFlow(flowId, { surface }))
    .filter(Boolean)
    .map((flow) => ({
      id: flow.id,
      label: flow.label,
      shortLabel: flow.shortLabel,
      audience: flow.audience,
      duration: flow.duration,
      summary: flow.summary,
      stepCount: flow.steps.length,
    }))
}
