from __future__ import annotations

import enum


class Role(enum.StrEnum):
    ADMIN = "ADMIN"
    OPS_MANAGER = "OPS_MANAGER"
    HR = "HR"
    FINANCE = "FINANCE"
    ASSISTANT_VALUER = "ASSISTANT_VALUER"
    FIELD_VALUER = "FIELD_VALUER"
    EMPLOYEE = "EMPLOYEE"
    EXTERNAL_PARTNER = "EXTERNAL_PARTNER"


class AssignmentStatus(enum.StrEnum):
    PENDING = "PENDING"
    SITE_VISIT = "SITE_VISIT"
    UNDER_PROCESS = "UNDER_PROCESS"
    SUBMITTED = "SUBMITTED"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"


class CaseType(enum.StrEnum):
    BANK = "BANK"
    EXTERNAL_VALUER = "EXTERNAL_VALUER"
    DIRECT_CLIENT = "DIRECT_CLIENT"


class ServiceLine(enum.StrEnum):
    VALUATION = "VALUATION"
    INDUSTRIAL = "INDUSTRIAL"
    DPR = "DPR"
    CMA = "CMA"


class TaskStatus(enum.StrEnum):
    TODO = "TODO"
    DOING = "DOING"
    DONE = "DONE"
    BLOCKED = "BLOCKED"


class ApprovalStatus(enum.StrEnum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"


class DocumentReviewStatus(enum.StrEnum):
    UPLOADED = "UPLOADED"
    RECEIVED = "RECEIVED"
    REVIEWED = "REVIEWED"
    NEEDS_CLARIFICATION = "NEEDS_CLARIFICATION"
    REJECTED = "REJECTED"
    FINAL = "FINAL"


class DocumentVisibility(enum.StrEnum):
    INTERNAL_ONLY = "INTERNAL_ONLY"
    PARTNER_RELEASED = "PARTNER_RELEASED"


class ApprovalEntityType(enum.StrEnum):
    ASSIGNMENT = "ASSIGNMENT"
    USER = "USER"
    INVOICE = "INVOICE"
    LEAVE = "LEAVE"


class ApprovalActionType(enum.StrEnum):
    FEE_OVERRIDE = "FEE_OVERRIDE"
    MARK_PAID = "MARK_PAID"
    DELETE_ASSIGNMENT = "DELETE_ASSIGNMENT"
    CLOSE_ASSIGNMENT = "CLOSE_ASSIGNMENT"
    RESET_PASSWORD = "RESET_PASSWORD"
    CHANGE_ROLE = "CHANGE_ROLE"
    REASSIGN = "REASSIGN"
    INVOICE_CREATE = "INVOICE_CREATE"
    INVOICE_UPDATE = "INVOICE_UPDATE"
    DOC_REQUEST = "DOC_REQUEST"
    FIELD_VISIT = "FIELD_VISIT"
    FINAL_REVIEW = "FINAL_REVIEW"
    CLIENT_CALL = "CLIENT_CALL"
    PAYMENT_FOLLOWUP = "PAYMENT_FOLLOWUP"
    EXCEPTION = "EXCEPTION"
    RESET_MFA = "RESET_MFA"


class LeaveType(enum.StrEnum):
    FULL_DAY = "FULL_DAY"
    HALF_DAY = "HALF_DAY"
    PERMISSION_HOURS = "PERMISSION_HOURS"


class LeaveStatus(enum.StrEnum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"


class CalendarEventType(enum.StrEnum):
    SITE_VISIT = "SITE_VISIT"
    REPORT_DUE = "REPORT_DUE"
    DOC_PICKUP = "DOC_PICKUP"
    INTERNAL_MEETING = "INTERNAL_MEETING"
    TASK_DUE = "TASK_DUE"
    PAYMENT_FOLLOWUP = "PAYMENT_FOLLOWUP"
    LEAVE = "LEAVE"


class NotificationType(enum.StrEnum):
    MISSING_DOC = "MISSING_DOC"
    SLA_DUE_SOON = "SLA_DUE_SOON"
    SLA_OVERDUE = "SLA_OVERDUE"
    PAYMENT_PENDING = "PAYMENT_PENDING"
    PARTNER_REQUEST_SUBMITTED = "PARTNER_REQUEST_SUBMITTED"
    PARTNER_REQUEST_NEEDS_INFO = "PARTNER_REQUEST_NEEDS_INFO"
    PARTNER_REQUEST_APPROVED = "PARTNER_REQUEST_APPROVED"
    PARTNER_REQUEST_REJECTED = "PARTNER_REQUEST_REJECTED"
    PARTNER_DOC_REQUESTED = "PARTNER_DOC_REQUESTED"
    PARTNER_DOC_SUBMITTED = "PARTNER_DOC_SUBMITTED"
    PARTNER_PAYMENT_REQUESTED = "PARTNER_PAYMENT_REQUESTED"
    PARTNER_PAYMENT_PROOF_SUBMITTED = "PARTNER_PAYMENT_PROOF_SUBMITTED"
    PARTNER_PAYMENT_VERIFIED = "PARTNER_PAYMENT_VERIFIED"
    PARTNER_DELIVERABLE_RELEASED = "PARTNER_DELIVERABLE_RELEASED"
    APPROVAL_PENDING = "APPROVAL_PENDING"
    APPROVAL_APPROVED = "APPROVAL_APPROVED"
    APPROVAL_REJECTED = "APPROVAL_REJECTED"
    MENTION = "MENTION"
    LEAVE_APPROVED = "LEAVE_APPROVED"
    LEAVE_REJECTED = "LEAVE_REJECTED"
    ASSIGNMENT_ASSIGNED = "ASSIGNMENT_ASSIGNED"
    ASSIGNMENT_REASSIGNED = "ASSIGNMENT_REASSIGNED"
    TASK_ASSIGNED = "TASK_ASSIGNED"
    TASK_UPDATED = "TASK_UPDATED"
    TASK_DUE_SOON = "TASK_DUE_SOON"
    TASK_OVERDUE = "TASK_OVERDUE"
    RELATIONSHIP_ALERT = "RELATIONSHIP_ALERT"


class NotificationChannel(enum.StrEnum):
    IN_APP = "IN_APP"
    EMAIL = "EMAIL"
    WHATSAPP = "WHATSAPP"


class NotificationDeliveryStatus(enum.StrEnum):
    PENDING = "PENDING"
    SENT = "SENT"
    FAILED = "FAILED"


class InvoiceStatus(enum.StrEnum):
    DRAFT = "DRAFT"
    ISSUED = "ISSUED"
    SENT = "SENT"
    PARTIALLY_PAID = "PARTIALLY_PAID"
    PAID = "PAID"
    VOID = "VOID"


class PaymentMode(enum.StrEnum):
    CASH = "CASH"
    BANK_TRANSFER = "BANK_TRANSFER"
    UPI = "UPI"
    CHEQUE = "CHEQUE"
    CARD = "CARD"
    MANUAL = "MANUAL"
    OTHER = "OTHER"


class InvoiceAdjustmentType(enum.StrEnum):
    CREDIT_NOTE = "CREDIT_NOTE"
    DISCOUNT = "DISCOUNT"
    WRITE_OFF = "WRITE_OFF"
    OTHER = "OTHER"


class CommissionRequestStatus(enum.StrEnum):
    DRAFT = "DRAFT"
    SUBMITTED = "SUBMITTED"
    NEEDS_INFO = "NEEDS_INFO"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    CONVERTED = "CONVERTED"


class PartnerRequestDirection(enum.StrEnum):
    INTERNAL_TO_PARTNER = "INTERNAL_TO_PARTNER"
    PARTNER_TO_INTERNAL = "PARTNER_TO_INTERNAL"


class PartnerRequestType(enum.StrEnum):
    DOC_REQUEST = "DOC_REQUEST"
    DOC_SUBMITTED = "DOC_SUBMITTED"
    PAYMENT_REQUESTED = "PAYMENT_REQUESTED"
    PAYMENT_PROOF_SUBMITTED = "PAYMENT_PROOF_SUBMITTED"
    FINAL_REPORT_RELEASED = "FINAL_REPORT_RELEASED"
    INFO_REQUEST = "INFO_REQUEST"
    REVISION_REQUEST = "REVISION_REQUEST"


class PartnerRequestEntityType(enum.StrEnum):
    COMMISSION_REQUEST = "COMMISSION_REQUEST"
    ASSIGNMENT = "ASSIGNMENT"
    INVOICE = "INVOICE"


class PartnerRequestStatus(enum.StrEnum):
    OPEN = "OPEN"
    RESPONDED = "RESPONDED"
    CLOSED = "CLOSED"


class WorkSessionType(enum.StrEnum):
    MANUAL = "MANUAL"
    AUTO = "AUTO"


class PartnerAccountRequestStatus(enum.StrEnum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"


class PayrollRunStatus(enum.StrEnum):
    DRAFT = "DRAFT"
    TIME_PENDING = "TIME_PENDING"
    READY_TO_CALCULATE = "READY_TO_CALCULATE"
    CALCULATED = "CALCULATED"
    APPROVED = "APPROVED"
    PAID = "PAID"
    LOCKED = "LOCKED"


class SalaryComponentType(enum.StrEnum):
    EARNING = "EARNING"
    DEDUCTION = "DEDUCTION"


class PayrollAdjustmentType(enum.StrEnum):
    BONUS = "BONUS"
    REIMBURSEMENT = "REIMBURSEMENT"
    DEDUCTION = "DEDUCTION"
    ADVANCE_RECOVERY = "ADVANCE_RECOVERY"
    OTHER = "OTHER"


class SupportThreadStatus(enum.StrEnum):
    OPEN = "OPEN"
    PENDING = "PENDING"
    RESOLVED = "RESOLVED"
    CLOSED = "CLOSED"


class SupportPriority(enum.StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    URGENT = "URGENT"


class AuthorType(enum.StrEnum):
    INTERNAL = "INTERNAL"
    EXTERNAL = "EXTERNAL"
