#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${ROOT_DIR}/.env"
BACKEND_ENV_FILE="${ROOT_DIR}/.env.backend"
REPOGEN_ENV_FILE="${ROOT_DIR}/deploy/repogen.env"

FORCE=0
if [[ "${1:-}" == "--force" ]]; then
  FORCE=1
fi

V1_DOMAIN="${V1_DOMAIN:-zenops.notalonestudios.com}"
REPOGEN_DOMAIN="${REPOGEN_DOMAIN:-app-zenops.notalonestudios.com}"
TRAEFIK_NETWORK="${TRAEFIK_NETWORK:-traefik-proxy}"
TRAEFIK_CERTRESOLVER="${TRAEFIK_CERTRESOLVER:-letsencrypt}"

POSTGRES_DB="${POSTGRES_DB:-zenops}"
POSTGRES_USER="${POSTGRES_USER:-zenops}"
POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-$(openssl rand -hex 16)}"
JWT_SECRET="${JWT_SECRET:-$(openssl rand -hex 48)}"

REPOGEN_POSTGRES_DB="${REPOGEN_POSTGRES_DB:-zenops}"
REPOGEN_POSTGRES_USER="${REPOGEN_POSTGRES_USER:-postgres}"
REPOGEN_POSTGRES_PASSWORD="${REPOGEN_POSTGRES_PASSWORD:-$(openssl rand -hex 16)}"
REPOGEN_JWT_SECRET="${REPOGEN_JWT_SECRET:-$(openssl rand -hex 48)}"

REPOGEN_STORAGE_DRIVER="${REPOGEN_STORAGE_DRIVER:-s3}"
REPOGEN_S3_ENDPOINT="${REPOGEN_S3_ENDPOINT:-https://<accountid>.r2.cloudflarestorage.com}"
REPOGEN_S3_REGION="${REPOGEN_S3_REGION:-auto}"
REPOGEN_S3_BUCKET="${REPOGEN_S3_BUCKET:-<your-r2-bucket>}"
REPOGEN_S3_ACCESS_KEY_ID="${REPOGEN_S3_ACCESS_KEY_ID:-<your-r2-key>}"
REPOGEN_S3_SECRET_ACCESS_KEY="${REPOGEN_S3_SECRET_ACCESS_KEY:-<your-r2-secret>}"
REPOGEN_S3_FORCE_PATH_STYLE="${REPOGEN_S3_FORCE_PATH_STYLE:-true}"
REPOGEN_S3_PUBLIC_BASE_URL="${REPOGEN_S3_PUBLIC_BASE_URL:-}"

V1_ADMIN_EMAIL="${V1_ADMIN_EMAIL:-admin@zenops.local}"
V1_ADMIN_PASSWORD="${V1_ADMIN_PASSWORD:-password}"

log() {
  printf '[bootstrap-pilot-env] %s\n' "$*"
}

fail() {
  printf '[bootstrap-pilot-env][FAIL] %s\n' "$*" >&2
  exit 1
}

write_file() {
  local path="$1"
  local content="$2"
  if [[ -f "$path" && "$FORCE" != "1" ]]; then
    fail "Refusing to overwrite existing file: $path (rerun with --force)"
  fi
  printf '%s\n' "$content" >"$path"
}

command -v openssl >/dev/null 2>&1 || fail "openssl is required"

write_file "$ENV_FILE" "COMPOSE_PROJECT_NAME=zenops
ZENOPS_DOMAIN=${V1_DOMAIN}
TRAEFIK_CERTRESOLVER=${TRAEFIK_CERTRESOLVER}

POSTGRES_DB=${POSTGRES_DB}
POSTGRES_USER=${POSTGRES_USER}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

VITE_API_URL=/api
VITE_V2_WEB_URL=https://${REPOGEN_DOMAIN}

BACKUP_HOST_PATH=/opt/zenops/backups
RETAIN_LOCAL_DAYS=21
RETAIN_REMOTE_DAYS=30
BACKUP_RETENTION_DAYS=21"

write_file "$BACKEND_ENV_FILE" "ENVIRONMENT=production
DATABASE_URL=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
JWT_SECRET=${JWT_SECRET}
ALGORITHM=HS256
ACCESS_TOKEN_EXPIRE_MINUTES=120
ALLOW_DESTRUCTIVE_ACTIONS=false

PUBLIC_BASE_URL=https://${V1_DOMAIN}
ALLOW_ORIGINS=https://${V1_DOMAIN}

UPLOADS_DIR=/app/uploads
MAX_UPLOAD_MB=25
AV_SCAN_ENABLED=0

ASSOCIATE_ONBOARDING_MODE=INVITE_ONLY
ASSOCIATE_EMAIL_VERIFY_REQUIRED=1
ASSOCIATE_VERIFY_TOKEN_TTL_MINUTES=15
ASSOCIATE_AUTO_APPROVE_DOMAINS=
ASSOCIATE_AUTO_APPROVE_MAX_PER_DAY=25

DB_POOL_SIZE=5
DB_MAX_OVERFLOW=10
DB_POOL_TIMEOUT=30
DB_POOL_RECYCLE=1800

RATE_LIMIT_LOGIN_IP_MAX=10
RATE_LIMIT_LOGIN_IP_WINDOW_SECONDS=60
RATE_LIMIT_LOGIN_EMAIL_MAX=5
RATE_LIMIT_LOGIN_EMAIL_WINDOW_SECONDS=60
RATE_LIMIT_REQUEST_ACCESS_IP_MAX=3
RATE_LIMIT_REQUEST_ACCESS_IP_WINDOW_SECONDS=86400
RATE_LIMIT_REQUEST_ACCESS_EMAIL_MAX=2
RATE_LIMIT_REQUEST_ACCESS_EMAIL_WINDOW_SECONDS=86400
RATE_LIMIT_PASSWORD_RESET_EMAIL_MAX=3
RATE_LIMIT_PASSWORD_RESET_EMAIL_WINDOW_SECONDS=3600"

write_file "$REPOGEN_ENV_FILE" "REPOGEN_DOMAIN=${REPOGEN_DOMAIN}
TRAEFIK_NETWORK=${TRAEFIK_NETWORK}
TRAEFIK_NETWORK_EXTERNAL=true
TRAEFIK_ENTRYPOINTS=websecure
TRAEFIK_CERTRESOLVER=${TRAEFIK_CERTRESOLVER}

REPOGEN_API_PORT=3000
REPOGEN_WEB_PORT=5174

REPOGEN_NODE_ENV=production
REPOGEN_LOG_LEVEL=info
REPOGEN_WORKER_CONCURRENCY=4
REPOGEN_MULTI_TENANT_ENABLED=false
REPOGEN_INTERNAL_TENANT_ID=11111111-1111-1111-1111-111111111111
REPOGEN_EXTERNAL_TENANT_ID=22222222-2222-2222-2222-222222222222
REPOGEN_JWT_SECRET=${REPOGEN_JWT_SECRET}

REPOGEN_POSTGRES_DB=${REPOGEN_POSTGRES_DB}
REPOGEN_POSTGRES_USER=${REPOGEN_POSTGRES_USER}
REPOGEN_POSTGRES_PASSWORD=${REPOGEN_POSTGRES_PASSWORD}
REPOGEN_DATABASE_URL_ROOT=postgresql://${REPOGEN_POSTGRES_USER}:${REPOGEN_POSTGRES_PASSWORD}@repogen-db:5432/${REPOGEN_POSTGRES_DB}
REPOGEN_DATABASE_URL_API=postgresql://zen_api:zen_api@repogen-db:5432/${REPOGEN_POSTGRES_DB}
REPOGEN_DATABASE_URL_WORKER=postgresql://zen_worker:zen_worker@repogen-db:5432/${REPOGEN_POSTGRES_DB}
REPOGEN_REDIS_URL=redis://repogen-redis:6379

REPOGEN_PUBLIC_API_BASE_URL=https://${REPOGEN_DOMAIN}/v1

REPOGEN_STORAGE_DRIVER=${REPOGEN_STORAGE_DRIVER}
REPOGEN_S3_ENDPOINT=${REPOGEN_S3_ENDPOINT}
REPOGEN_S3_REGION=${REPOGEN_S3_REGION}
REPOGEN_S3_BUCKET=${REPOGEN_S3_BUCKET}
REPOGEN_S3_ACCESS_KEY_ID=${REPOGEN_S3_ACCESS_KEY_ID}
REPOGEN_S3_SECRET_ACCESS_KEY=${REPOGEN_S3_SECRET_ACCESS_KEY}
REPOGEN_S3_FORCE_PATH_STYLE=${REPOGEN_S3_FORCE_PATH_STYLE}
REPOGEN_S3_PUBLIC_BASE_URL=${REPOGEN_S3_PUBLIC_BASE_URL}

V1_BASE_URL=https://${V1_DOMAIN}
REPOGEN_BASE_URL=https://${REPOGEN_DOMAIN}
REPOGEN_WEB_URL=https://${REPOGEN_DOMAIN}
V1_ADMIN_EMAIL=${V1_ADMIN_EMAIL}
V1_ADMIN_PASSWORD=${V1_ADMIN_PASSWORD}"

log "Generated:"
log "  ${ENV_FILE}"
log "  ${BACKEND_ENV_FILE}"
log "  ${REPOGEN_ENV_FILE}"
log ""
log "Next:"
log "  1) Replace any R2 placeholder values in ${REPOGEN_ENV_FILE}"
log "  2) Run: ./ops/up_pilot_hostinger.sh"
log "  3) Run: ./ops/smoke_deploy_repogen.sh"

