#!/usr/bin/env bash
#
# Zen Ops Hostinger deployment workflow
# pull -> pre-migration backup -> migrate -> up -> readiness/smoke
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$REPO_ROOT"

DEFAULT_COMPOSE_FILE="docker-compose.hostinger.yml"
if [ ! -f "$DEFAULT_COMPOSE_FILE" ]; then
  DEFAULT_COMPOSE_FILE="docker-compose.yml"
fi

COMPOSE_FILE="${COMPOSE_FILE:-$DEFAULT_COMPOSE_FILE}"
COMPOSE_PROJECT_NAME="${COMPOSE_PROJECT_NAME:-zenops}"
HEALTH_TIMEOUT="${HEALTH_TIMEOUT:-180}"
HEALTH_INTERVAL="${HEALTH_INTERVAL:-3}"
BACKUP_DIR="${BACKUP_DIR:-deploy/backups}"

COMPOSE=(docker compose -f "$COMPOSE_FILE" -p "$COMPOSE_PROJECT_NAME")

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log() {
  echo -e "${GREEN}[$(date +'%Y-%m-%d %H:%M:%S')]${NC} $*"
}

warn() {
  echo -e "${YELLOW}[$(date +'%Y-%m-%d %H:%M:%S')] WARNING:${NC} $*" >&2
}

error() {
  echo -e "${RED}[$(date +'%Y-%m-%d %H:%M:%S')] ERROR:${NC} $*" >&2
  exit 1
}

compose() {
  "${COMPOSE[@]}" "$@"
}

wait_for_db() {
  local timeout="${1:-120}"
  local elapsed=0
  while [ "$elapsed" -lt "$timeout" ]; do
    if compose exec -T db sh -lc 'pg_isready -U "$POSTGRES_USER" -d "$POSTGRES_DB"' >/dev/null 2>&1; then
      return 0
    fi
    sleep 2
    elapsed=$((elapsed + 2))
  done
  return 1
}

if [ ! -f "$COMPOSE_FILE" ]; then
  error "Compose file not found: $COMPOSE_FILE"
fi

log "Using compose file: $COMPOSE_FILE"
log "Using compose project: $COMPOSE_PROJECT_NAME"

log "Validating compose configuration..."
compose config -q

mkdir -p "$BACKUP_DIR" ops/releases

current_image_for() {
  local service="$1"
  local cid
  cid="$(compose ps -q "$service" 2>/dev/null || true)"
  if [ -z "$cid" ]; then
    echo ""
    return 0
  fi
  docker inspect --format '{{.Config.Image}}' "$cid" 2>/dev/null || true
}

PREV_API_IMAGE="$(current_image_for api)"
PREV_FRONTEND_IMAGE="$(current_image_for frontend)"
PREV_WORKER_IMAGE="$(current_image_for email-worker)"

STATE_FILE="ops/releases/previous-images.env"
cat > "$STATE_FILE" <<EOF
# Generated by ops/deploy.sh
COMPOSE_FILE=${COMPOSE_FILE}
COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}
CAPTURED_AT=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
PREVIOUS_API_IMAGE=${PREV_API_IMAGE}
PREVIOUS_FRONTEND_IMAGE=${PREV_FRONTEND_IMAGE}
PREVIOUS_EMAIL_WORKER_IMAGE=${PREV_WORKER_IMAGE}
EOF
log "Saved rollback state to $STATE_FILE"

log "Step 1/5: Pulling images (best effort)..."
if ! compose pull --ignore-pull-failures; then
  warn "Some images could not be pulled; continuing (local build may be used)."
fi

log "Ensuring database is running for backup/migration..."
compose up -d db
if ! wait_for_db 120; then
  error "Database did not become ready in time"
fi

log "Step 2/5: Creating pre-migration pg_dump backup..."
TS="$(date -u +'%Y%m%dT%H%M%SZ')"
PRE_MIGRATION_BACKUP="$BACKUP_DIR/pre_migration_${TS}.sql.gz"

if ! compose exec -T db sh -lc 'PGPASSWORD="$POSTGRES_PASSWORD" pg_dump -h 127.0.0.1 -U "$POSTGRES_USER" "$POSTGRES_DB"' | gzip -9 > "$PRE_MIGRATION_BACKUP"; then
  rm -f "$PRE_MIGRATION_BACKUP"
  error "Pre-migration backup failed"
fi

if [ ! -s "$PRE_MIGRATION_BACKUP" ]; then
  error "Backup file was created but is empty: $PRE_MIGRATION_BACKUP"
fi
log "Pre-migration backup created: $PRE_MIGRATION_BACKUP"

log "Step 3/5: Running migrations (alembic upgrade head)..."
compose run --rm migrate

log "Step 4/5: Starting application services..."
compose up -d db api frontend email-worker

log "Step 5/5: Waiting for API readiness (/readyz)..."
ELAPSED=0
READY_PAYLOAD=""

while [ "$ELAPSED" -lt "$HEALTH_TIMEOUT" ]; do
  READY_PAYLOAD="$(compose exec -T api curl -fsS http://127.0.0.1:8000/readyz 2>/dev/null || true)"
  if echo "$READY_PAYLOAD" | grep -q '"status"[[:space:]]*:[[:space:]]*"ok"'; then
    break
  fi
  sleep "$HEALTH_INTERVAL"
  ELAPSED=$((ELAPSED + HEALTH_INTERVAL))
done

if [ -z "$READY_PAYLOAD" ]; then
  error "API readiness check failed after ${HEALTH_TIMEOUT}s"
fi

log "API ready: $READY_PAYLOAD"

echo ""
echo "========================================"
echo "Zen Ops deploy completed"
echo "========================================"
if [ -n "${ZENOPS_DOMAIN:-}" ]; then
  echo "Web URL:   https://${ZENOPS_DOMAIN}"
  echo "API URL:   https://${ZENOPS_DOMAIN}/api"
  echo "Ready URL: https://${ZENOPS_DOMAIN}/readyz"
else
  echo "Set ZENOPS_DOMAIN to print public HTTPS URLs"
fi

echo ""
echo "Smoke checklist:"
echo "  1) Login works"
echo "  2) Assignments list loads"
echo "  3) Assignment detail opens"
echo "  4) Documents upload + preview works"
echo "  5) Admin pages load (Master Data / Personnel / Support / Backups)"
echo ""
echo "Rollback helpers:"
echo "  - image rollback: ./ops/rollback.sh"
echo "  - DB restore (manual): see README Hostinger restore section"
echo ""
